// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var demoTask, fill, food, foods, name, numbers, shortNames, test, _i, _len, _ref;
    demoTask = function(start, end) {
      return end - start;
    };
    foods = ['broccoli', 'spinach', 'chocolate'];
    for (_i = 0, _len = foods.length; _i < _len; _i++) {
      food = foods[_i];
      if (food !== 'chocolate') {
        eat(food);
      }
    }
    test = function(x) {
      return x * 2;
    };
    fill = function(container, liquid) {
      if (liquid == null) {
        liquid = "coffee";
      }
      return "Filling the " + container + " with " + liquid + "...";
    };
    shortNames = (function() {
      var _j, _len1, _results;
      _results = [];
      for (_j = 0, _len1 = list.length; _j < _len1; _j++) {
        name = list[_j];
        if (name.length < 5) {
          _results.push(name);
        }
      }
      return _results;
    })();
    numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    [].splice.apply(numbers, [3, 4].concat(_ref = [-3, -4, -5, -6])), _ref;
    return window.like({
      ss: "nihak"
    });
  });

}).call(this);
